### PR TITLE
make compatible with string-only schedule

### LINKED ISSUE #16: scheduleRate.startsWith is not a function
I am getting the error: `scheduleRate.startsWith is not a function` while using the plugin. I am using version `1.0.4` with serverless version `2.53.0`.

Here is how my schedule looks like:
`events:
      - schedule:
          description: "Test"
          rate: "rate(2 minutes)"
          enabled: true
`
I did try logging where the error appeard to come form and i see:

Scheduled Event:  [ 'rate(2 minutes)' ]

It seems to be an Array and `.startsWith` fails as its not a string in function: `exports.convertExpressionToCron`

### PR DESCRIPTION
**Pull request by MichaelCharles**
This is a recreation of an old pull request I made and then recinded when deleting my fork of the repository. It seems like it might still be helpful to some. I haven't independantly tested this again though, so it might be better if someone tested it before merging it.

I'm not actively working on a Serverless framework project at the moment, and so testing it myself is a bit difficult right now. If my schedule frees up I'll take a look at it.

The following is the text of the original pull request.

----

For me and seemingly for other users event["schedule"] itself is simply a string with the schedule expression (e.g rate(10 days), cron(*/10 * * * * *) as opposed to the object which is currently expected by the code.

This request will change the code to account for when event["schedule"] is a string in a non-breaking way.

This should resolve #16

### CODE REVIEW

**Comment by MichaelCharles** [comment]
Here is the original pull request by the way: https://github.com/Meemaw/serverless-offline-schedule/pull/25

File: typings/Serverless/index.d.ts [hunk 1]
```diff
@@ -35,7 +35,9 @@ declare namespace Serverless {
     extraServicePath?: string;
   }
 
-  type Event = { [type: string]: { rate: string; input?: object } };
+  type Event = {
+    schedule: { rate: string; input?: object } | string;
```
Comment (eliakaris) [inline typings/Serverless/index.d.ts:39]: there's also an enabled field which could be used and respected in the code if enabled: false

**Review by dtsuper3 — APPROVED** [review]

**Review by Meemaw — APPROVED** [review]
